version: "3.9"

services:

  catmash_front:
    container_name: catmash_front
    environment:
      - "REACT_APP_CATMASH_API_URL=http://localhost:8090"
    build: ./catmash-front
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - "3000:3000"
    depends_on:
      - catmash_api

  catmash_api:
    build: ./CatMashAPI
    container_name: catmash_api
    restart: always
    ports:
      - "8090:8090"
    links:
      - catmash_db
    depends_on:
      - catmash_db

  catmash_db:
    image: mysql:8
    container_name: catmash_db
    volumes:
      - ./mysql-db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=application
      - MYSQL_DATABASE=catmash_db

# networks:
#   name: catmash_network