version: "3.9"

services:

  catmash_api:
    build: ./CatMashAPI
    container_name: catmash_api
    restart: always
    ports:
      - "8090:8090"
    links:
      - catmash_db
    depends_on:
      - catmash_db

  catmash_db:
    image: mysql:8
    container_name: catmash_db
    volumes:
      - ./mysql-db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=application
      - MYSQL_DATABASE=catmash_db
